<?php

/**
 * AuthTokenTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AuthTokenTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AuthTokenTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AuthToken');
    }
}