<?php

/**
 * AuthToken
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    station_manager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AuthToken extends BaseAuthToken
{
  public function __toString() {
    return $this->token;
  }
  
  /**
  * Set's the remote address.
  *
  * @param $address A string containing the remote address.
  */
  public function setRemoteAddress($address) {
    $this->_set('remote_address', ip2long($address));
  }
  
  /**
  * Overrides the save method to set a token if one wasn't explicitly given.
  */
  public function save(Doctrine_Connection $conn = null) {
    if ($this->isNew() && $this->token == null) {
      $this->token = sha1($this->User->salt.$this->remote_address.$this->remote_port.time());
    }
    
    return parent::save($conn);
  }
}
