<?php

/**
 * Process
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    station_manager
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Process extends BaseProcess
{
  /**
  * This overload converts the last pulse into a human readable format.
  */
  public function getLastPulse() {
    $ptime = strptime($this->_get('last_pulse'), "%Y%m%d%H%M%S"); 
    
    return strftime('%A, %d %B %Y %T'.$ptime['unparsed'].' %Z', 
      mktime($ptime['tm_hour'], 
             $ptime['tm_min'], 
             $ptime['tm_sec'], 
             $ptime['tm_mon']+1, 
             $ptime['tm_mday'], 
             $ptime['tm_year'] + 1900));
  }
}
