Cluster:
    connection: server_directory
    actAs: { Timestampable: ~ }
    columns:
        primary_id: integer
        name: string(100)
        status: integer
    relations:
        Process:
            onDelete: SET NULL
            local: primary_id
        
Process:
    connection: server_directory
    actAs: { Timestampable: ~ }
    columns:
        cluster_id: integer
        type:
            type: enum
            values: [watchdog, login, connection]        
        version: string(255)
        address: integer
        tcp_port: integer
        udp_port: integer
        status: integer
        last_pulse: 
            type: decimal(17)
            scale: 3
    relations:
        Cluster:
            onDelete: CASCADE
            foreignAlias: Processes
        